# Generated by Django 6.0.2 on 2026-03-09 18:51

import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdocument',
            name='hardcopy_file',
            field=models.FileField(blank=True, null=True, upload_to=projects.models.project_hardcopy_upload_path),
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='user_fields',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='verification',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
