# Generated by Django 6.0.2 on 2026-03-14 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectdocument_hardcopy_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('issue', 'Issue'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
