# Generated by Django 6.0.2 on 2026-03-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdocument',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('issue', 'Issue'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
